runtime: nodejs22
service: default

handlers:
    - url: /
      static_files: build/index.html
      upload: build/index.html
    - url: /(.*)
      static_files: build/\1
      upload: build/(.*)

env_variables:
    REACT_APP_BACKEND_GATEWAY_URL: https://backend-dot-citizen-science-app-for-kids.wn.r.appspot.com
